name: digital_store
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  fancy_shimmer_image: ^2.0.1+1
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.3
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
  google_fonts: ^2.2.0
  introduction_screen: ^2.1.0
  loader_overlay: ^2.0.5
  sqflite: ^2.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:

  color: "#ffffff"

  image: "assets/images/new-logo.png"
  color_dark: "#ffffff"
  image_dark: "assets/images/new-logo.png"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/new-icon.png"
flutter:
  assets:
    - assets/images/

  uses-material-design: true
